version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - BRANCH=dev   # Specify the branch you want to deploy
      - PORT=5000    # Specify the host port
    ports:
      - "${PORT}:5000"
